use_frameworks!
platform :ios, '16.0'

target 'RenderCloud_Example' do
  pod 'RenderCloud', :path => '../'
  pod 'FirebaseAuth'
  pod 'FirebaseDatabase'

  target 'RenderCloud_Tests' do
    inherit! :search_paths
  end
end
